### PR TITLE
Fix missing error handling

### PR DESCRIPTION
**Pull request by shubham14bajpai**
Signed-off-by: shubham <shubham14bajpai@gmail.com>

## Why is this needed

The err checked in line 265 is the error from the previous function call and the error from line 264 is not being handled. The fix captures the error at the correct place.

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]

**Review by jacobweinstock — APPROVED** [review]

**Comment by markyjackson-taulia** [comment]
Also, thank you for the PR and welcome to the community!

**Comment by markyjackson-taulia** [comment]
@shubham14bajpai this is the test cmd/tink-worker/internal/worker.go#L264

**Comment by shubham14bajpai** [comment]
> @shubham14bajpai this is the test cmd/tink-worker/internal/worker.go#L264

There is no _test file for worker.go Should I add one with a test case for `ProcessWorkflowActions` function?

**Comment by markyjackson-taulia** [comment]
Yes please

**Comment by shubham14bajpai** [comment]
> Yes please

I need a little help with that. I haven't written much tests around grpc clients. Can you guide me how to mock the `WorkflowServiceClient` in the Worker object? Should I use gomock or is there a better way to do that?

**Comment by markyjackson-taulia** [comment]
@shubham14bajpai I have been really enjoying testify/mock. You can get a idea of the test mindset [here](https://github.com/argoproj/argo-workflows/blob/507b92cf93337e18e3f64716081a797e0f60973e/cmd/argo/commands/resubmit_test.go)

**Comment by gauravgahlot** [comment]
@shubham14bajpai Could please update the branch and also fix the CI issue?

**Review by jacobweinstock — APPROVED** [review]
While this doesn't have tests, I feel comfortable approving.

**Review by nicklasfrahm — APPROVED** [review]

**Pull request merged**
