### PR TITLE
Fixed: duplicate key value violates unique constraint while creating multiple workflows

### PR DESCRIPTION
**Pull request by gauravgahlot**
## Why is this needed

Fixes: #379 

## How Has This Been Tested?

1. `git clone https://github.com/kinvolk/terraform-provider-tinkerbell && cd terraform-provider-tinkerbell`
2. build new images with changes in place and update docker-compose file
3. `docker-compose -f test/docker-compose.yml up -d`
4. `TF_ACC=1 TINKERBELL_GRPC_AUTHORITY=127.0.0.1:42113 TINKERBELL_CERT_URL=http://127.0.0.1:42114/cert go test -v -run=^TestAccWorkflow_.*$ -count 100 ./tinkerbell/`

### CODE REVIEW

**Comment by gianarb** [comment]
@gauravgahlot I think you have to create a separate migration :) so if we have people running the previous version they will be able to move from the master to this one

**Review by gianarb — CHANGES_REQUESTED** [review]
@gauravgahlot I think you have to create a separate migration :) so if we have people running the previous version they will be able to move from the master to this one

**Review by invidian — COMMENTED** [review]
I didn't get time to test it yet, but from what I've seen, it should fix the issue. Scheme also looks sensible, though some explanation in commit message would be nice, so one don't have to figure it out on their own.

**Comment by gianarb** [comment]
Reading the comment @invidian said I think it will be nice to actually have that documentation as a comment in the migration function itself! ❤️

**Comment by mmlb** [comment]
> Reading the comment @invidian said I think it will be nice to actually have that documentation as a comment in the migration function itself! heart

This is probably a good idea in general for all migrations :D

**Review by invidian — APPROVED** [review]
LGTM

**Review by gianarb — APPROVED** [review]

**Pull request merged**
