### PR TITLE
Remove packet protobuf

### PR DESCRIPTION
**Pull request by gianarb**
This should not be required and I can't see we use it

Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

### CODE REVIEW

**Comment by gianarb** [comment]
Hegel uses it

**Comment by mmlb** [comment]
You know I think we should probably promote it as the metadata value and then later replace it with Instance proposal. I don't think we want all the things here in Instance. But actually, the problem with promoting this to hardware.metadata is that it then becomes hard for other people to extend how ever they want ...

**Comment by gianarb** [comment]
What do you mean expanded as they want? Metadata are the contract used from
tink worker and boots it can't be whatever we want.

I understand it is to be flexible but a well designed structure can allow
that I suppose

**Comment by gianarb** [comment]
Ok I suppose we are not ready for this, if you want to discuss about this topic I think the right issue is https://github.com/tinkerbell/tink/issues/359

**Pull request closed without merging**
