### PR TITLE
Database interface refactor

### PR DESCRIPTION
**Pull request by micahhausler**
Signed-off-by: Micah Hausler <mhausler@amazon.com>

## Description

This includes 4 changes that are preparatory for future work to migrate to the Kubernetes data model.

* Propagate stream context in streaming API. Previously `context.Background()` was used, but the stream provides a context object
* Refactored shadowed "context" package name. By naming a method variable "context", no `context` package calls could be made in the method
* Added `context.Context` to `GetWorkflowsForWorker()` database API. This plumbs down the context from the API call into the `d.instance.QueryContext()` call.
* Refactor the database interface. I added a new interface `WorkerWorkflow` with the methods that get used by APIs the Tink Worker invokes. This is essentially a no-op for now. 

## Why is this needed

See tinkerbell/proposals#46

## How Has This Been Tested?

Locally ran tests.

## How are existing users impacted? What migration steps/scripts do we need?

No impact to existing users

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by mmlb — APPROVED** [review]

**Comment by mmlb** [comment]
Hey @micahhausler can you split this into a few commits please? I'm thinking:

- rename context -> ctx
- change context.Background -> stream.Context
- add context to GetWorkflowsForWorker
- everything else

looks to be the best break down to me.

**Comment by micahhausler** [comment]
>

> Hey @micahhausler can you split this into a few commits please? I'm thinking:
> 
> * rename context -> ctx
> * change context.Background -> stream.Context
> * add context to GetWorkflowsForWorker
> * everything else
> 
> looks to be the best break down to me.

For an already small change is breaking it down further more of a preference or is there a documented style guide? I'm happy to do it if you think its necessary

**Comment by mmlb** [comment]
> For an already small change is breaking it down further more of a preference or is there a documented style guide? I'm happy to do it if you think its necessary

There is not a style guide covering this, which is unfortunate and I will remedy that soon. Looking at the history of PRs to this and other tinkerbell repos I think we've all pretty much landed on one-commit-per-change, more or less.

**Comment by mmlb** [comment]
Also, I'll channel my @tstromberg senses and ask you to please update the PR description with info for all the changes being submitted. This way we can be sure the changes are intentional.

**Comment by micahhausler** [comment]
> Also, I'll channel my @tstromberg senses and ask you to please update the PR description with info for all the changes being submitted. This way we can be sure the changes are intentional.

Done! I think CI is now waiting for some sort of maintainer approval

**Review by mmlb — APPROVED** [review]

**Pull request merged**
