### PR TITLE
Add Vendordata to metadata

### PR DESCRIPTION
**Pull request by displague**
## Description

Adds a vendordata key to the metadata structure.  This will be used by tinkerbell/hegel#62
## How are existing users impacted? What migration steps/scripts do we need?

The addition of a vendordata path will allow for differentiation between "userdata" and "vendordata" as described in https://cloudinit.readthedocs.io/en/latest/topics/vendordata.html

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by jacobweinstock** [comment]
@chrisdoherty4, mind taking a look at this?

**Comment by chrisdoherty4** [comment]
This seems OK for the Kube back-end. Do we need anything in the database? Do we need a discussion around continued database support?

**Comment by chrisdoherty4** [comment]
I think we're good to merge this!

**Review by chrisdoherty4 — DISMISSED** [review]

**Comment by displague** [comment]
rebased

**Review by jacobweinstock — APPROVED** [review]

**Pull request merged**
