### PR TITLE
Add functionality for users to retrieve template by Name as well as UUID

### PR DESCRIPTION
**Pull request by Belchy06**
Signed-off-by: William Belcher <william.belcher@hotmail.com>

## Description

This PR adds the ability for Tink to retrieve workflows by either UUID or by Name. If the value after `tink template get` is not a valid UUID, Tink will default to searching for the value in the Name field of the templates. 

This PR also adds a TemplateClient to the Tink client, allowing other services such as Boots to retrieve templates.

## Why is this needed

This feature is required for the project I am working on but I am sure there are many other use cases I'm unaware of. Also, https://github.com/tinkerbell/boots/issues/178

## How Has This Been Tested?
This has been tested in the VM's based on the [Local Setup with Vagrant](https://docs.tinkerbell.org/setup/local-vagrant/) tutorial, as well as in our personal deployment

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by Belchy06** [comment]
@tstromberg I have once again accidentally closed my last PR... Doh!!

Here is a new one with the minor tweaks you requested. Let me know if there's anything else you'd like touched up!

**Comment by jacobweinstock** [comment]
Hey @Belchy06, looks like a couple of checks and a merge conflict need attention. Anything I can do to help with this?

**Comment by mmlb** [comment]
Hey @Belchy06 can you rebase on top of latest main, I've done a bunch of work fixing the generators so the edit you made to template.pb.go should be unnecessary.

**Comment by mmlb** [comment]
@Belchy06 I've rebased on top of main and tweaked your PR a little further. Can you verify that "Allow edits from maintainers" is checked? I'd like to update with my changes in [pull-541-tweaks](https://github.com/mmlb/tink/tree/pull-541-tweaks). I still get confused whether or not that will actually work with organization type repos. If not I'll just open up a separate PR (4th time's the charm!)

**Comment by nshalman** [comment]
> @Belchy06 I've rebased on top of main and tweaked your PR a little further. Can you verify that "Allow edits from maintainers" is checked? I'd like to update with my changes in [pull-541-tweaks](https://github.com/mmlb/tink/tree/pull-541-tweaks). I still get confused whether or not that will actually work with organization type repos. If not I'll just open up a separate PR (4th time's the charm!)

@Belchy06 is this something you're still working on?

**Comment by mmlb** [comment]
I'd say lets close this and I'll PR my branch that is based on this one.

**Comment by mmlb** [comment]
I've opened up a draft PR (https://github.com/tinkerbell/tink/pull/541) that should replace this one. It's still a draft because I have not tested it myself.

**Pull request closed without merging**
