### PR TITLE
Fix for #435, Create cli for tink

### PR DESCRIPTION
**Pull request by parauliya**
Signed-off-by: parauliya <aman@infracloud.io>

## Description

Reusable tink create cli

## Why is this needed
Fixes: #435 

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by gianarb** [comment]
Hey @parauliya as we spoke yesterday I have implemented the common feature and the structure of the create command.

You should not deference NEVER any resource inside the `create` pkg. This is the only way to stay resource agnostic. When you have doubt look at `delete`, `get`.

have a look at the `doc.go` file for the `create` package to have an idea about where I am going with it.

I realized too late that I introduced the `--file` that is something we probably don't want. I am not sure and I don't know how cobra supports what @mmlb suggests like `- <path_file>`. @mmlb do you know? Also, I think it opens the door for more questions:

* can you create multiple resources in one command if you pass multiple files? `- <path_file1> `- <path_file2>` or should we fail? 
* If the multiple resource creation is something we want I think we have to reevaluate the strategy to reconcile `flags` with the content passed via `stdin`, or `file` because if it is not a single resource is harder to reconcile (right now flags override what gets passed via `stdin`, `file`.

**Comment by mmlb** [comment]
> I realized too late that I introduced the `--file` that is something we probably don't want. I am not sure and I don't know how cobra supports what @mmlb suggests like `- <path_file>`. @mmlb do you know? 

No I don't know, but I would _assume_ cobra will have 2 left over args after processing: `-` and `<path_file>`.

Also, I think it opens the door for more questions:
> 
>     * can you create multiple resources in one command if you pass multiple files? `- <path_file1> - <path_file2>` or should we fail?

Would be nice to process them all, imo.

> 
>     * If the multiple resource creation is something we want I think we have to reevaluate the strategy to reconcile `flags` with the content passed via `stdin`, or `file` because if it is not a single resource is harder to reconcile (right now flags override what gets passed via `stdin`, `file`.

Have an example of this?

**Comment by gianarb** [comment]
> Have an example of this?

I want to get to a point where you can even pass a file or a stdin or if available for a resource you can use flags. Workflows are the ones I have in my mind right now.

You can use flags:

```
$ tink workflow create \
  --template-id CA321BBF-2AE0-4B45-AAE3-076C894FA282 \
  --data device_1=AF:E8:60:85:A6:CF \
  --data address=192.168.1.12
```

You can get it from stdin:

```
cat ./workflows.yaml | tink workflow create
```

Probably workflow.yaml will look like:

```yaml
templateID: CA321BBF-2AE0-4B45-AAE3-076C894FA282
data:
  - device_1: AF:E8:60:85:A6:CF
  - address: 192.168.1.12
```

In theory, if we assume you can create only one resource at a time we can merge flags over a stdin/file. But if we take more files, I think we should error because we won't know how to merge it:

```
cat ./workflows.yaml | tink workflow create --data device_1=5D:8B:43:28:66:21
```

If we go with:

```
 tink workflow create -- <file1>
```

The UX enables the user to think that they can add more paths (just as you do with git for example), so if we decide that we don't want to support multiple resources (because we don't know how to merge flags, or to avoid explaining it to end-users), I think we should avoid a UX that is not self-explanatory.   

Those are the options I see:

* Declare that only one resource can be created at the time
* Error if stdin/file AND flags are passed at the same time (this will allow us to accept stdin or files that have multiple resources)
* Accept everything and explain all the rules we onboarded, but this is error-prone and not that user friendly

**Comment by mmlb** [comment]
Ah yeah `workflow create` is a weird beast here. It would be cool if viper did something like `--template id1 --device foo --device bar --template id2 --device baz`, but I think it probably makes more sense to rethink differently here. I think either we take in one/many files like you show as path or stdin and/or allow flags to define only 1 workflow and everything comes in from flags. I would not really miss the flags going away.

**Comment by gianarb** [comment]
> I would not really miss the flags going away.

This is a hard sentence. Currently, today workflows for example only get created via flags... So in theory you are saying you won't miss the requirement of writing your workflows to a file in order to create one. This makes scripting a bit more complicated.

I think flags play a role in the update command, not really related to create but I expect the update command to supports the same flags a create has to do something like a PATCH. If we remove flags all together it means we will update only via file (extract the current version, modify and "apply")

**Comment by mmlb** [comment]
@gianarb 

> > I would not really miss the flags going away.
> 
> This is a hard sentence. Currently, today workflows for example only get created via flags... So in theory you are saying you won't miss the requirement of writing your workflows to a file in order to create one. This makes scripting a bit more complicated.

Not really:
```sh
for mac in mac1 mac2 mac3; do
  tink workflow create <<-EOF
    templateID: CA321BBF-2AE0-4B45-AAE3-076C894FA282
    data:
      - device_1: $mac
  EOF
```
or any other way to build up stdin which isn't too bad and why I say I wouldn't miss flags going away.

If you do want to keep them then it would be ok to do just one workflow at a time and only via flags.

I don't really feel strongly either way. I'd be fine with making `workflow create` look like all the other commands in that they don't take flags.

> I think flags play a role in the update command, not really related to create but I expect the update command to supports the same flags a create has to do something like a PATCH. If we remove flags all together it means we will update only via file (extract the current version, modify and "apply")
> 
> NB: Weird to speak about update for workflows that technically should be immutable (I think)

Yeah, I'm still like -0 on updating a template/workflow. I'd rather it just be a new template instead. Leaving "update" logic out to a different service/program/user. If someone _really_ wants it then fine but I don't really see the use case.

**Comment by mmlb** [comment]
> Yeah, I'm still like -0 on updating a template/workflow. I'd rather it just be a new template instead. Leaving "update" logic out to a different service/program/user. If someone _really_ wants it then fine but I don't really see the use case.

Ooops I was thinking of updating a template not a workflow, which is what I'm -0 for. I'm very much -2/NAK for updating a workflow. That should be immutable. You didn't like the workflow your're running then cancel it and start a new one.

**Comment by splaspood** [comment]
Looks like there have been some good points made by a number of people back in March. What would it take for us to come to consensus around these changes?

**Comment by tstromberg** [comment]
Closing this PR as stale. Please reopen this PR when you are ready to retake a look at it. Thank you for your contribution!

**Pull request closed without merging**
