### PR TITLE
Events are cleaned up if the resource is deleted

### PR DESCRIPTION
**Pull request by gauravgahlot**
## Description

Going forward if a resource (template, hardware, workflow, ...) is deleted, all the events for that particular resource will also be cleaned up (irrespective of configured TTL).

## Why is this needed

Fixes: #396 

## How Has This Been Tested?

- Manually over vagrant setup
- Unit Tests

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by gianarb** [comment]
I am still not 100% sure that this is a valuable solution. Or the solution we want. And I want to ask @invidian to help me with this.

@gauravgahlot this issue has a problem, it is deleting all the events for a particular resource when it gets deleted. It also deletes the event that notifies that a resource is deleted I presume, it means that users and applications that rely on events to synchronize an external system or to build automation will have issues dealing with a deletion. 

Excluding the event kind `DELETED` will be enough?

If a user wrote something like an "audit logger" that tracks all the actions made via Tinkerbell with an event TTL of 1h. The extension for some reason stays offline for 30 minutes and in that our hardware gets created, updated, and deleted it will be impossible to reconstruct that part of the history. IMPOSSIBLE because events are not stored anywhere anymore.

I still think events should be immutable with the only exception of the garbage collector part. How Kubernetes handle this problem for example? Do we know? 

Thanks

**Comment by gauravgahlot** [comment]
AFAIK, if we delete a resource in Kubernetes we can still get its events using `kubectl get event`(including `DELETED` event). And after a TTL (default is 1hr I think) those events are gone. 

I'm glad most of the work in the PR is around tests and not the fix itself. 😄 
I was anyway going to extract the test commits to a separate PR and only leave the fix and its unit tests here.

**Comment by gianarb** [comment]
well done @gauravgahlot but now that you said how Kubernetes works I will take it as a confirmation that this is a feature we should not implement 👍

**Comment by invidian** [comment]
IMO Documenting the TTL for Tinkerbell events (whatever it is or whatever is planned) should be sufficient to resolve #396 :+1:

**Comment by gianarb** [comment]
Great, I will close this for now, about doc, atm I don't know where to write about it! I have to figure it out

**Pull request closed without merging**
