### PR TITLE
Run in Kubernetes

### PR DESCRIPTION
**Pull request by mrchrd**
## Description

This adds an option to deploy Tinkerbell using Kubernetes (k3s) instead of Docker Compose.

## Why is this needed

This allows Tinkerbell to run in Kubernetes. This will enable further development like Helm Charts, Operators, etc.

## How Has This Been Tested?

Manually tested the Hello World workflow.

## How are existing users impacted? What migration steps/scripts do we need?

There's no impact. Users can use Kubernetes by setting up environment variable `USE_KUBERNETES=true` in `envrc`, or before launching `vagrant up` or `generate-envrc.sh`. Leaving the variable undefined or setting it to `false` will use Docker Compose as expected.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by detiber** [comment]
@mrchrd After speaking with @gianarb we thought it would be best if we moved the kubernetes work to a separate repository, similar to https://github.com/tinkerbell/sandbox.

I went ahead and created https://github.com/tinkerbell/k8s-sandbox. Do you mind porting the work in this PR over to that repository?

**Comment by mrchrd** [comment]
Then, in order to avoid duplicating code, I suggest that:
- Deployment scripts and assets are removed from the tink repository; and
- Either:
  - This PR is moved to the existing sandbox repository; or
  - We move the content of the kindDev branch to the k8s-sandbox directory (and forget this PR).

**Comment by detiber** [comment]
@mrchrd My apologies for not elaborating more, my suggestion was to start the k8s-sandbox with the work you have from this PR, and then I would port over my kindDev branch work to that repo, rebasing on top of the work you've done.

The goal is indeed to remove deployment scripts and assets from this repository completely.

**Comment by mrchrd** [comment]
https://github.com/tinkerbell/k8s-sandbox/pull/3

**Pull request closed without merging**
