### PR TITLE
Drop the events system

### PR DESCRIPTION
**Pull request by gauravgahlot**
## Description

The PR removes all the code and DB changes related to the events system.

## Why is this needed

Fixes: #464 

## How Has This Been Tested?

- Existing unit tests
- Manual tests

## How are existing users impacted? What migration steps/scripts do we need?

This is a breaking change, especially for any users currently using events.
If your tool is not using tink events the migration should be smooth.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by gianarb** [comment]
@detiber do you mind to have a look at this please?

**Comment by moadqassem** [comment]
@gauravgahlot So once this PR is merged, the 8000 bytes limit from the triggers will be solved right?

**Comment by gauravgahlot** [comment]
> @gauravgahlot So once this PR is merged, the 8000 bytes limit from the triggers will be solved right?

@moadqassem After this PR is merged there will no event triggers at all. 😄

**Review by gianarb — APPROVED** [review]

**Review by detiber — APPROVED** [review]
lgtm

**Pull request merged**
