### PR TITLE
[WIP] e2e test for vagrant setup

### PR DESCRIPTION
**Pull request by gianarb**
## Description

This PR uses vagrant to spin up VMs and it execute automatically the [Vagrant Setup](https://tinkerbell.org/setup/local-with-vagrant/)

## Why is this needed

We would like to get automatically tested the Vagrant Setup guide because it has to work in order to offer a great first impression to the community.

Fixes: #169 

## How Has This Been Tested?

This code tests things by design 😎

## How are existing users impacted? What migration steps/scripts do we need?

No impact

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [x] provided instructions on how to upgrade

### CODE REVIEW

**Comment by mrmrcoleman** [comment]
@gianarb It's probably a good idea to update the README to explain a little bit about how this works, in case people need to debug build failures or add new steps.

**Comment by gianarb** [comment]
Thanks @mrmrcoleman ! The PR does not even work yet! I will be sure to add everything I can add troubleshooting and debug

**Comment by mrmrcoleman** [comment]
@gianarb molto bene!

**Comment by gianarb** [comment]
At this point we are in the position where:

```
go test -v ./test/_vagrant
```
This command will run the Vagrant Getting Started. The package is called `_vagrant` because by default `go test` does not look at packages that start with `_`. This is an easy trick to exclude tests that should not run as part of the `go test ./...` made at the root of the project.

**Comment by gianarb** [comment]
I realized this PR does not have a lot of sense. The e2e tests use `./setup.sh` and it downloads `:latest` from Docker Registry.  So we are not testing against that code.

I still think this is valuable as a workflow and at least as getting started for something that will be useful as soon as we define a release workflow and a starter `startup.sh`.

At the end the goal was to have a test case for Vagrant and this is what it is.

**Pull request merged**
