### PR TITLE
Upgrade package jsonpb to protojson.

### PR DESCRIPTION
**Pull request by rahulgrover99**
Signed-off-by: Rahul Grover <rahulgrover99@gmail.com>

## Description
Upgrades `package github.com/golang/protobuf/jsonpb` to `google.golang.org/protobuf/encoding/protojson` 

## Why is this needed
`package github.com/golang/protobuf/jsonpb` is deprecated.

Fixes: Staticcheck error. SA1019

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Thank you for this pr and welcome to the community!

**Comment by gauravgahlot** [comment]
@rahulgrover99 Could you please update the branch and fix the CI issues?

**Comment by rahulgrover99** [comment]
@gauravgahlot I was going through the checks that failed. It looks like the lint check failed because of the use of deprecated packages in `db/template.go`. Will it be a good idea to add `nolint:staticcheck` to those imports?
Also, another fail is because of no test coverage of the changes I made. Could you help me out with that as well? I am not sure what tests might help cover these changes.

**Review by tstromberg — APPROVED** [review]

**Comment by tstromberg** [comment]
Thank you for your PR!

**Pull request merged**
