### PR TITLE
feat: add otel plumbing & grpc instrumentation

### PR DESCRIPTION
**Pull request by tobert**
## Description

This PR adds OpenTelemetry plumbing and gRPC instrumentation to tink. When configured as described in the README, this will cause tink components to emit otel tracing data to the configured service, which enables observability of requests across tink components.

Note: I couldn't seem to avoid updating some dependencies when I made these changes so there are some mostly-unrelated changes due to that, most notably, the Docker library and required API changes.

## How Has This Been Tested?

Current tests seem to pass. Still need to add more tests which is why this is a draft PR for now.

## How are existing users impacted? What migration steps/scripts do we need?

Currently the only way to trace requests across the tink stack is with logs and we'd like to improve on that.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [x] provided instructions on how to upgrade
- [ ] move to an otel-launcher that is supported (currently using @tobert's branch)

### CODE REVIEW

**Comment by Raj-Dharwadkar** [comment]
@tobert, I see this in draft for additional tests. Please let us know if any help required.

**Comment by tobert** [comment]
> @tobert, I see this in draft for additional tests. Please let us know if any help required.

This was blocked on some work I'm doing in otel-init-go so we don't use a hacked-up launcher. I finished up the bulk of that work yesterday in https://github.com/equinix-labs/otel-init-go/pull/2 and once that's merged I'll come back around and touch this up ready for review.

**Comment by tobert** [comment]
Most of those weird security vulnerabilities should go away when I revise this for otel 1.0.0-RC2.

**Comment by tobert** [comment]
While going through OSIE I realized I need to do some work in tink-worker and started that. I can tack that onto this PR or follow up. I should have something to look at in the middle of next week.

**Comment by tstromberg** [comment]
> While going through OSIE I realized I need to do some work in tink-worker and started that. I can tack that onto this PR or follow up. I should have something to look at in the middle of next week.

Let's put that into a follow-up PR.

**Comment by tstromberg** [comment]
Can you run `prettier` on the README.md? It seems there is a github action that checks for it:

```
[warn] README.md
789
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

(cue rant about linting markdown docs...)

**Comment by tobert** [comment]
I've pushed up the prettier changes @tstromberg

**Comment by tstromberg** [comment]
Looks like your PR is blocked on #529 (codespell doesn't like your go.mod file) - #530 may need to be  merged first.

**Comment by tobert** [comment]
Wow, fun. This is totally breaking my branch. I'll figure it out.

**Review by tstromberg — APPROVED** [review]

**Pull request merged**
