### PR TITLE
Add GitHub issue and PR templates

### PR DESCRIPTION
**Pull request by alexellis**
## Title

Add GitHub issue and PR templates

## Description

These GitHub templates aim to improve the level of detail on
pull requests and issues raised by the team, to make the
external community feel more welcome and part of the project.

These are copyright to OpenFaaS Ltd, but we are happy to
contribute them under the license of this project for use by
Packet / Tinkerbell.

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

### CODE REVIEW

**Comment by grahamc** [comment]
I wonder if we should create a tinkerbell/.github repository to hold things like this? especially since docs should be updated in multiple places, and the same rules apply for most repos.

**Comment by alexellis** [comment]
A central place for the change would be good, but I can't contribute that, it would need an admin. How about merging this, and then doing whatever you need to with your Tinkerbell org superpowers?

**Comment by grahamc** [comment]
I just created https://github.com/tinkerbell/.github -- would you mind relocating the PR there?

**Comment by alexellis** [comment]
Done: https://github.com/tinkerbell/.github/pull/1

**Pull request closed without merging**
