### PR TITLE
Rework build tool installation

### PR DESCRIPTION
**Pull request by chrisdoherty4**
Using `go run` has proven to be slower than installing tools. This PR changes all tools to be installed in `out/tools` and fixes unnecessary reinstallations.

### CODE REVIEW

**Review by jacobweinstock — APPROVED** [review]
Too much Make! 😝

**Comment by chrisdoherty4** [comment]
@mergify queue

**Comment by chrisdoherty4** [comment]
@mergify refresh

**Comment by chrisdoherty4** [comment]
@mergify queue

**Pull request merged**
