### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jacobsmith928**
Added simple reference to Packet and Equinix.

### CODE REVIEW

**Comment by nathangoulding** [comment]
Let’s include osie, and also tinkerbell -> tink now. Thanks!

**Comment by alexellis** [comment]
@parauliya is there a public issue (I think JIRA must be internal?) that discusses the change to remove the target concept?

**Comment by parauliya** [comment]
> @parauliya is there a public issue (I think JIRA must be internal?) that discusses the change to remove the target concept?

@alexellis, There is a following public issue:
[Issue #60 ](https://github.com/tinkerbell/tink/issues/60)
And there is a wiki page where all the discussion mentioned:
[RFC #1 ](https://github.com/tinkerbell/tink/wiki/RFC-%231---Merge-Hardware-and-Target-models)

**Comment by parauliya** [comment]
I am closing this pull request and raising a new pull request for the same purpose:
https://github.com/tinkerbell/tink/pull/127

**Pull request closed without merging**
