### PR TITLE
Add v1alpha2 API

### PR DESCRIPTION
**Pull request by chrisdoherty4**
Design: https://github.com/tinkerbell/roadmap/blob/main/design/20230222_tinkerbell_crd_refactor.md

This PR adds the new v1alpha2 API. The APIs are configured as unserved meaning consumers won't be able to request the v1alpha2 version yet.

Webhooks will be added in a separate PR.

### CODE REVIEW

**Comment by chrisdoherty4** [comment]
@moadqassem Yes. I've never seen a dedicated list CRD generated. Normally the list type is part of the CRD definition. I'm guessing I have something funky with my annotations.

**Comment by moadqassem** [comment]
> @moadqassem Yes. I've never seen a dedicated list CRD generated. Normally the list type is part of the CRD definition. I'm guessing I have something funky with my annotations.
> 
> I generated a new project with `kubebuilder` and did a quick cross reference but couldn't see anything.

Did you try to add `+kubebuilder:object:generate=false` to your Objects ?

**Comment by chrisdoherty4** [comment]
@moadqassem I'll give that a go, but that didn't exist in our v1alpha1 API and reflecting on other projects they don't seem to have it either (and they don't have list resources).

**Comment by moadqassem** [comment]
> @moadqassem I'll give that a go, but that didn't exist in our v1alpha1 API and reflecting on other projects they don't seem to have it either (and they don't have list resources).

I agree, would check also the genclient version, maybe something changed.

**Comment by chrisdoherty4** [comment]
@moadqassem We have lift off 🚀 .

**Review by jacobweinstock — APPROVED** [review]
thanks @chrisdoherty4

**Pull request merged**
