### PR TITLE
Changing file permissions

### PR DESCRIPTION
**Pull request by soniasingla**
Changing file permissions

### CODE REVIEW

**Review by markyjackson-taulia — COMMENTED** [review]
Can you elaborate on why the permissions need changing?

**Comment by markyjackson-taulia** [comment]
Also, thank you for this pr and welcome to the community

**Comment by soniasingla** [comment]
> Can you elaborate on why the permissions need changing?

musdev bot saying its a security error under GOSEC,`G302 Expect file permissions to be 0600 or less`

**Comment by gauravgahlot** [comment]
Closing in favor of #498

**Pull request closed without merging**
