### PR TITLE
(bugbash) fixes potential file inclusion via variable.

### PR DESCRIPTION
**Pull request by rahulgrover99**
Signed-off-by: Rahul Grover <rahulgrover99@gmail.com>

## Description
gosec was showing the following warning "Potential file inclusion via variable". This is because we are trying to open files using dynamic variables. Hence, I've cleaned the bad file paths using filepath.Clean()

Fixes: 
G304 Potential file inclusion via variable

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Thank you for this pr and welcome to the community

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
We'll need better test coverage before we can approve and merge. Let me know if you need any help with that.

**Comment by rahulgrover99** [comment]
Oh, I thought the changes won't require any test coverage. Can you please point me to where I could get started for this?

**Comment by markyjackson-taulia** [comment]
> We'll need better test coverage before we can approve and merge. Let me know if you need any help with that.

@rahulgrover99 take a look at the current set of test and see if you can add

**Review by nshalman — APPROVED** [review]
All the Codecov complaints are warnings, and this seems like a good change from a security perspective so I will be merging it. Thank you!

**Pull request merged**
