### PR TITLE
fix getWorkerID when mac addresses have captalized letters

### PR DESCRIPTION
**Pull request by moadqassem**
## Why is this needed
To solve the worker not found errors, when the mac address of the worker is in upper case. 

Fixes: #485

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by tstromberg** [comment]
This PR looks great - is there any way we could have a unit test added to ensure that we don't break this again in the future?

**Comment by moadqassem** [comment]
@tstromberg you can extend this case here https://github.com/tinkerbell/tink/blob/master/db/workflow_test.go#L42-L68 and and then do a fetch request or workflow get request with a device id that has the characters lower cases

**Comment by gauravgahlot** [comment]
Hey @moadqassem, do you mind updating the branch and extend the test as well? It would be great to merge the PR then.

**Comment by moadqassem** [comment]
@gauravgahlot I have added a test case to cover that https://github.com/tinkerbell/tink/pull/486/commits/d502edecbbad8a9144aa587b9967bc1bd454e5a2 

cc @tstromberg

**Review by gauravgahlot — APPROVED** [review]

**Comment by gauravgahlot** [comment]
Thank you @moadqassem :rocket:

**Pull request merged**
