### PR TITLE
update contributor experience

### PR DESCRIPTION
**Pull request by jacobweinstock**
## Description

Getting started with the Tinkerbell stack and through this Tink repo the local development path, for me, had a few hurdles. 

- I found it difficult to understand and spin up Tink without diving deep into the code.
- I haven't been able to generate TLS certificates locally using the scripts found in this repo. They were all very coupled to vagrant with virtualbox.
- There were a lot of environment variables that were difficult to understand what to set them to without, again, diving deep into the code.
- `make run` did not work for me.
```bash
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```
- Documentation was difficult to find

This PR adds `make run` and `make run-clean` to allow spin up and down a docker-compose tink, tink-cli, db stack. PR updates the server and cli dockerfiles and adds a top level docker-compose.yaml. 

## Why is this needed

Fixes: https://github.com/tinkerbell/tink/issues/417

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [x] provided instructions on how to upgrade

### CODE REVIEW

**Comment by gianarb** [comment]
Great initiative. The development experience in Tinkerbell is not something that I am personally really involved with but I know @mmlb has opinions as well.

Overall the `directory` folder as we know it can be away or change drastically. I would like to avoid more files or ways to developer I think we should just have one that works for a good amount of people. 

Now sure which one, overall what I don't like is the fact that it adds another docker-compose file without removing anything

**Comment by mmlb** [comment]
Hey @jacobweinstock I agree with @gianarb re multiple docker-compose files. Can you try to merge them? I think yours is the one to keep. For example, I think we can drop the tls cert stuff and registry container. I'm also not sure we need the connections to tink-servr via 127.0.0.1 and can just use docker-compose's dns.

**Comment by jacobweinstock** [comment]
@gianarb @mmlb , just to clarify are we talking about the `deploy` directory and `deploy/docker-compose.yml`? 

Also, would the prefered location for the new updated `docker-compose.yml` file in this PR be top-level or in the `deploy` directory or somewhere else?

**Comment by mmlb** [comment]
@jacobweinstock yep getting rid of the deploy/docker-compose.yml is what I'd like to see. deploy was started from before we had the sandbox so I think having the files here be tailored for development is what makes the most sense.

**Comment by jacobweinstock** [comment]
I will close this PR. I'll create new PRs. one to be just docs and create another PR for code changes.

**Pull request closed without merging**
