### PR TITLE
Added a new rpc call workflow.GetWorkflowContextList to be used by boots

### PR DESCRIPTION
**Pull request by gauravgahlot**
## Description
As the worker starts, Boots checks [if there is a workflow](https://github.com/tinkerbell/boots/blob/master/packet/endpoints.go#L48) defined for that worker. If yes, it will continue to PXE and it will not otherwise. (more context [here](https://github.com/tinkerbell/boots/pull/50)).

The PR introduces a new RPC that can be used by Boots to get the workflow contexts without having to maintain a gRPC stream. 

## Why is this needed

Recently there have been [changes](https://github.com/tinkerbell/tink/issues/222) in Tink, to allow a worker to maintain a gRPC stream with the server to get the workflows. The same RPC was being by boots. 

## How Has This Been Tested?
Still a WIP. 

## How are existing users impacted? What migration steps/scripts do we need?

No direct impact on users.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by Cbkhare** [comment]
Let me first test it with boots then merge it.

**Comment by Cbkhare** [comment]
changes done in accordance with https://github.com/tinkerbell/tink/issues/238

**Comment by Cbkhare** [comment]
Tested the workflow execution using this PR. changes are working correctly.
For more ref follow https://github.com/tinkerbell/boots/pull/64

**Comment by Cbkhare** [comment]
> Can we write a unit test for this?! I would like to have a table test that insert a set of fixtures and checks what we expect. This is a crucial part of the application @gauravgahlot can you add that to this PR?

@gianarb Will it be fine if we merge this PR and @gauravgahlot can add table test for it in a separate PR. To fix issues related to #222 , this is a kind of priority.

**Comment by gianarb** [comment]
Yes I agree but let's get it done as soon as it is merged please

**Comment by Cbkhare** [comment]
> Yes I agree but let's get it done as soon as it is merged please

Thanks @gianarb ,

**Pull request merged**
