### PR TITLE
Remove extra space from CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by soniasingla**
Bugsmash!!

### CODE REVIEW

**Review by markyjackson-taulia — COMMENTED** [review]
Thank you for your PR and welcome to the community.
There does not appear to be any changes here 🤔 Am I missing them?

**Comment by soniasingla** [comment]
@markyjackson-taulia hey! this PR basically cleans the documentation, wiping off unnecessary white-spaces 🤗

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by soniasingla** [comment]
@markyjackson-taulia ping ;)

**Review by markyjackson-taulia — APPROVED** [review]

**Review by jacobweinstock — APPROVED** [review]

**Comment by gauravgahlot** [comment]
@soniasingla Could you please fix the CI issue? So that we can move the PR ahead.

**Comment by soniasingla** [comment]
@gauravgahlot updated! 🎉

**Comment by markyjackson-taulia** [comment]
@soniasingla Let me see why the lint is failing. Gove me about 15 mins..

**Comment by jacobweinstock** [comment]
digging into this a little, I believe this PR will always fail the `For each commit and PR / ci-checks` because `prettier`, the app that does the markdown linting, is configured through `.editorconfig` to have `indent_size = 4` which requires markdown to have these extra spaces. Hope all this makes sense.

The extra spacing like this in the markdown files is definitely not what I'm used to but it appears to be the standard at the moment.

**Comment by soniasingla** [comment]
@jacobweinstock let me know, otherwise we can close this PR! 🤗

**Comment by jacobweinstock** [comment]
> @jacobweinstock let me know, otherwise we can close this PR! 🤗

Hey @soniasingla. Unfortunately, I think we should close this PR. Thank you for submitting though!

**Comment by soniasingla** [comment]
Thanks for letting me know!

**Pull request closed without merging**
